# Generated by Django 5.0 on 2023-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_details',
            name='year_of_passing',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
